# ===============================================
# Configuration Spring Boot
# ===============================================
spring:
  application:
    name: commande-service

  # --- Configuration Cloud SQL (méthode recommandée) ---
  # Ces propriétés sont utilisées par spring-cloud-gcp-starter-sql pour auto-configurer la connexion.
  cloud:
    gcp:
      sql:
        # Le nom de connexion de l'instance Cloud SQL
        instance-connection-name: "gcp-project-20250702:europe-west1:microservices-db"
        # Le nom de la base de données DANS l'instance
        database-name: "commande_db"

  # --- Configuration générale de la source de données ---
  datasource:
    # Pas besoin de spécifier l'URL ici, le starter s'en chargera pour vous !
    username: root
    # Utilisez une variable d'environnement pour le mot de passe, c'est une meilleure pratique.
    password: mi@nDR1s04

  # --- Configuration JPA ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

# ===============================================
# Configuration des propriétés personnalisées
# ===============================================
service:
  produit:
    url: https://produit-service-usut6o4i3q-ew.a.run.app/produits

app:
  pubsub:
    topic-name: commandes-creees

# ===============================================
#       CONFIGURATION POUR LE DÉVELOPPEMENT LOCAL
#    (À activer en décommentant et en utilisant un profil 'dev')
# ===============================================

# Pour utiliser cette section, lancez l'application avec le profil 'dev' :
# - Dans votre IDE, ajoutez dans les VM options : -Dspring.profiles.active=dev
# - En ligne de commande : mvn spring-boot:run -Dspring-boot.run.profiles=dev

#spring:
#  config:
#    activate:
#      on-profile: dev # Ces propriétés ne s'appliquent que si le profil 'dev' est actif
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/commande_db?createDatabaseIfNotExist=true
#    username: root
#    password: mi@nDR1s04 # Votre mot de passe local
#
#service:
#  produit:
#    url: http://localhost:8082